version: '3'
services:
  cassandra-db:
    hostname: cassandra-1
    image: cassandra:3.11.11
    command: /bin/bash -c "sleep 1 && echo ' -- Pausing to let system catch up ... -->' && /docker-entrypoint.sh cassandra -f"
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7199:7199"
      - "9042:9042"
      - "9160:9160"

  seed:
    build: ./
    links:
      - cassandra-db
    depends_on:
      - cassandra-db
    environment:
      CLUSTER_IP: seed
      CLUSTER_PORT: 1600
      SEED_PORT_1600_TCP_ADDR: seed
      CASSANDRA_CONTACT_POINT1: cassandra-db:9042
    entrypoint:
      [ "java", "-Dconfig.resource=cluster-application-docker.conf", "-jar", "/etc/akka/app.jar" ]

  cluster1:
    build: ./
    links:
      - cassandra-db
    depends_on:
      - cassandra-db
    environment:
      CLUSTER_IP: cluster1
      CLUSTER_PORT: 0
      SEED_PORT_1600_TCP_ADDR: seed
      CASSANDRA_CONTACT_POINT1: cassandra-db:9042
    entrypoint:
      [ "java", "-Dconfig.resource=cluster-application-docker.conf", "-jar", "/etc/akka/app.jar" ]

  cluster2:
    build: ./
    links:
      - cassandra-db
    depends_on:
      - cassandra-db
    environment:
      CLUSTER_IP: cluster2
      CLUSTER_PORT: 0
      SEED_PORT_1600_TCP_ADDR: seed
      CASSANDRA_CONTACT_POINT1: cassandra-db:9042
    entrypoint:
      [ "java", "-Dconfig.resource=cluster-application-docker.conf", "-jar", "/etc/akka/app.jar" ]

  endpoint:
    build: ./
    environment:
      CLUSTER_IP: endpoint
      CLUSTER_PORT: 0
      SEED_PORT_1600_TCP_ADDR: seed
    entrypoint:
      [ "java", "-Dconfig.resource=endpoint-application-docker.conf", "-jar", "/etc/akka/app.jar" ]
    depends_on:
      - seed
    ports:
      - "8082:8082"
